import razorpay
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from typing import Dict, Any

from app.schemas.policy import IntentPolicy, DecisionResult
from app.evaluator.rules import evaluate_cart_against_policy
from app.core.config import settings
from app.compiler.intent_engine import generate_policy_signature

router = APIRouter()

# Initialize Razorpay Client with credentials from settings
rzp_client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))

class InterceptedCheckoutRequest(BaseModel):
    checkout_payload: Dict[str, Any] = Field(
        ...,
        description="Standard Razorpay order creation payload including line_items, amount, currency, etc."
    )
    policy: IntentPolicy = Field(
        ...,
        description="The signed IntentPolicy envelope generated by the Intent Compiler."
    )

@router.post("/v1/orders")
async def create_intercepted_order(request: InterceptedCheckoutRequest):
    """
    Razorpay IntentGuard Proxy Endpoint:
    Intercepts agent checkout payloads and validates them against signed intent policies before order creation.
    """
    policy = request.policy
    checkout = request.checkout_payload

    # 1. Cryptographic HMAC Verification
    unsigned_payload = {
        "intent_id": str(policy.intent_id),
        "user_id": policy.user_id,
        "rules": policy.rules.model_dump(),
        "expires_at": policy.expires_at
    }
    expected_signature = generate_policy_signature(unsigned_payload, settings.POLICY_HMAC_SECRET)
    
    if policy.signature != expected_signature:
        raise HTTPException(
            status_code=401,
            detail="Security Violation: IntentPolicy HMAC signature mismatch or policy tampering detected."
        )

    # 2. Semantic & Monetary Policy Verification
    decision: DecisionResult = evaluate_cart_against_policy(checkout, policy)

    # 3. Gateway Decision Dispatcher
    if decision.status == "APPROVED":
        # Convert amount to paise for Razorpay API
        order_amount_paise = int(checkout.get("amount", 0) * 100)
        
        order_data = {
            "amount": order_amount_paise,
            "currency": checkout.get("currency", "INR"),
            "receipt": checkout.get("receipt", f"receipt_{policy.user_id}"),
            "notes": {
                "intent_id": str(policy.intent_id),
                "verified_by": "Razorpay-IntentGuard-v1",
                **checkout.get("notes", {})
            }
        }
        
        try:
            rzp_order = rzp_client.order.create(data=order_data)
            return {
                "status": "APPROVED",
                "message": "Cart payload successfully passed all semantic and budget intent checks.",
                "razorpay_order": rzp_order
            }
        except Exception as e:
            raise HTTPException(
                status_code=500,
                detail=f"Razorpay Order Execution Failed: {str(e)}"
            )

    elif decision.status == "AMBIGUOUS":
        return {
            "status": "HOLD",
            "reason": decision.reason,
            "escalation_id": decision.escalation_id,
            "message": "Transaction placed on hold. Triggered human-in-the-loop escalation approval."
        }

    else: # VIOLATION
        raise HTTPException(
            status_code=400,
            detail={
                "status": "BLOCKED",
                "reason": decision.reason,
                "message": "Transaction blocked due to clear Intent Policy violation."
            }
        )